### ISSUE TITLE
Rice theorem

### ISSUE THREAD

**Issue by mshibatatt** [mshibatatt/wcbc_problems#38]
論点を整理したので、ご確認お願いします。
https://github.com/mshibatatt/wcbc_problems/blob/main/problemsets/chapter7/rice.md

**Comment by miiitomi** [comment]
## @mshibatatt の [ライスの定理に関する議論](https://github.com/mshibatatt/wcbc_problems/blob/main/problemsets/chapter7/rice.md) についてコメント
### 予想の証明について
 - `ProgramIsMemberQ.py`は入力されたプログラムPがQに含まれるなら"yes", そうでないなら"no"を返す神託関数という理解で正しい?
 - ならば, (P, I)ががYesOnStringの正インスタンスでも, `alterYesToProgram.py`は「Qに含まれるプログラムを返すプログラム」になるだけであって, `alterYesToProgram.py`がQに含まれるかどうかはわからないから, `val == "yes"`とは限らないのでは?
 - 同様に(P,I)がYesOnStringの負インスタンスでも, `alterYesToProgram.py`がQに含まれないことは保証されないから, `val == "no"`とは限らないと思う.

### 補足
 - もし仮に, 「2つのプログラムが, すべての入力に対し同様の出力/例外を返す(もしくはどちらも無限ループする)のであれば, その2つのプログラムは同じものとして扱う」という前提を置くのであれば, `alterYesToProgram.py`を以下のようにすれば, 予想は成り立ちそう.
 ```python
import utils
from utils import rf
from universal import universal 

def alterYesToProgram(inString):
    progString = rf('progString.txt')
    newInString = rf('inString.txt')
    val = universal (progString, newInString)
    if val == 'yes':
        return universal(rf('F.py'), inString) # FはQに含まれるプログラム
    else:
        return universal(rf('G.py'), inString) # GはQに含まれないプログラム
```
 - だが例にあるように, 異なるステップ数がかかるプログラムは別のプログラムとみなすのであれば, この予想をこの方針で証明することは難しそう.

**Comment by mshibatatt** [comment]
ProgramIsMemberQ自体はとても大きなクラスの問題であり, Qの取り方次第で例えばComputeFとなり決定不能であるし, また, Q={あるプログラムP1と一言一句同じである}とすれば決定可能である.

`yesViaProgram`について6行目を以下のように書き換えれば本来意図した通りの設計ではあるが, 実行途中に`universal (progString, newInString)`が走ることになる. これが無限ループのときにはYesOnString問題は解けていない.
```
val = ProgramIsMemberQ(universal(rf('alterYesToProgram.py'), \varepsilon)))
```
