### ISSUE TITLE
Chapter 5 の解答

### ISSUE THREAD

**Issue by kazuyanagimoto** [mshibatatt/wcbc_problems#41]
@takumiyoshikawa chapter5_yoshikawa.ipynb は吉川の解答ではなく、冨田の。
@tokuma09 chapter5の解答がない。

**Comment by tokuma09** [comment]
chapter5の解答はグラフを書くのが面倒で紙で書いてる

捨てちゃったので、必要であれば、再度解くかな

**Comment by kazuyanagimoto** [comment]
まぁ、私たちへの貢献と言う意味では薄いけど、後世のためにって感じかな。もしやってくれるなら、[unify_chapter5](https://github.com/mshibatatt/wcbc_problems/tree/unify_chapter5)で作業してるので、そこに（別ファイルで）プッシュしてくれると嬉しい。chapter5.ipynbを見てもらえれば分かると思うけど、TMファイルを書けば、遷移図もシミュレーションもできるようになっている。

**Comment by tokuma09** [comment]
おっけー！
さすがにちょっと思い出さないといけないので明日すぐにできるかはわからないけど、この勉強会終了時までにはやります！
